package com.kotlin.education.android.easytodo.model

import androidx.room.*
import com.google.gson.annotations.SerializedName

/**
 * Represents a single task inside the application.
 * It is serializable so it can be send using intentf
 * The task must always has a name.
 * The Task is a data class. It means, that it just holds the data and has no
 * extra functionality. The getter and setters are generated automatically.
 */
@Entity(tableName = "tasks")
data class Task(@ColumnInfo(name = "name")var name: String?) {

    constructor() : this(null)

    // the database id. It is a instance of the class to be
    // able to set it null and check for it
    @PrimaryKey
    @ColumnInfo(name = "id")
    var id : Long? = null
    // task note
    @ColumnInfo(name = "note")
    var note : String? = null
    // task due date.
    @ColumnInfo(name = "dueDate")
    var dueDate : Long? = null
    // task images represented by the name of the file.
    // the problem is that we cannot save list to database. We need to specify how
    // the list will be saved. We will save the list to json and than convert it back to list
    // using the TaskTypeConverters class.
    @ColumnInfo(name = "images")
    var images: ArrayList<String>? = null
    // marks if task is done or not.
    @ColumnInfo(name = "done")
    var done : Boolean = false
    // the latitude of the task
    @ColumnInfo(name = "latitude")
    var latitude : Double? = null
    // the longitude of the task
    @ColumnInfo(name = "longitude")
    var longitude : Double? = null
    // the id of the notification generated by AndroidJob library
    @ColumnInfo(name = "notificationId")
    var notificationId : Int? = null

    // TODO Homework: For each task, store the time when it was marked as done.

}